source 'https://github.com/CocoaPods/Specs.git'

target 'SWTiltTransition' do
  use_frameworks!

  pod "SWTiltTransition", :path => "../"

  target 'Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end
