source 'https://github.com/CocoaPods/Specs.git'

target 'SWTiltTransition', :exclusive => true do
  pod "SWTiltTransition", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SWTiltTransition", :path => "../"

  
end
